### PR TITLE
About Us Page

### PR DESCRIPTION
**Pull request by KhajasJS**

### CODE REVIEW

**Comment by KhajasJS** [comment]
Preview is available at https://khajasjs.github.io/pewaukee-watershed.github.io/.

**Comment by KhajasJS** [comment]
@MakironiMan Can you work on the actual content of the `us/index.html` file?

**Review by KhajasJS — COMMENTED** [review]
# Strange Css
@secnyt There is strange css behavior that might be from the main page boxes.

## Screenshot
Screenshot 2020-11-03 at 10 54 04 AM

## Live Example
The live example can be seen at https://khajasjs.github.io/pewaukee-watershed.github.io/us/. This may look different in the future when more commits are created.

**Review by secnyt — APPROVED** [review]
Great! I approve.

**Review by MakironiMan — APPROVED** [review]
I approve. Good work!

**Pull request merged**
