### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by MakironiMan**
Look for vulnerabilities in the code.

### CODE REVIEW

**Comment by KhajasJS** [comment]
@MakironiMan Why is this needed?

**Comment by MakironiMan** [comment]
> @MakironiMan Why is this needed?

@KhajasJS to look for vulnerabilities in the code.

**Review by KhajasJS — APPROVED** [review]
I am fine with it if @secnyt is fine with it. Let's wait for @secnyt to review.

**Review by secnyt — CHANGES_REQUESTED** [review]
No, is useless, WHY.

Changes: delete it

**Comment by secnyt** [comment]
fine

**Pull request merged**
